# Generated by Django 3.2.5 on 2021-08-17 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remark', models.CharField(choices=[('working_day', 'Working Day'), ('holiday', 'Holiday'), ('half_day', 'Half Day'), ('function_day', 'Function Day/Special Day')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.designation')),
            ],
        ),
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.staff')),
                ('left_data', models.TextField()),
                ('right_data', models.TextField()),
                ('center_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot_in', models.TimeField()),
                ('time_slot_out', models.TimeField()),
                ('time_slot_mid', models.TimeField()),
            ],
            options={
                'unique_together': {('time_slot_in', 'time_slot_out')},
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.timeslot'),
        ),
        migrations.AddField(
            model_name='designation',
            name='time_slot_mid',
            field=models.ForeignKey(db_column='time_slot_mid', on_delete=django.db.models.deletion.CASCADE, to='main.timeslot'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.TimeField(null=True)),
                ('out_time', models.TimeField(null=True)),
                ('work_duration', models.CharField(max_length=64, null=True)),
                ('forenoon_remarks', models.CharField(max_length=64, null=True)),
                ('afternoon_remarks', models.CharField(max_length=64, null=True)),
                ('total_remarks', models.CharField(max_length=64, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.date')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
